// 10x-cards-angular/src/app/shared/components/table/table.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-table',
  template: `
    <div class="relative w-full overflow-auto">
      <table [ngClass]="['w-full caption-bottom text-sm', class]">
        <ng-content></ng-content>
      </table>
    </div>
  `,
  standalone: true,
  imports: [CommonModule]
})
export class TableComponent {
  @Input() class?: string;
}

@Component({
  selector: 'app-table-header',
  template: `
    <thead [ngClass]="['[&_tr]:border-b', class]">
      <ng-content></ng-content>
    </thead>
  `,
  standalone: true,
  imports: [CommonModule]
})
export class TableHeaderComponent {
  @Input() class?: string;
}

@Component({
  selector: 'app-table-body',
  template: `
    <tbody [ngClass]="['[&_tr:last-child]:border-0', class]">
      <ng-content></ng-content>
    </tbody>
  `,
  standalone: true,
  imports: [CommonModule]
})
export class TableBodyComponent {
  @Input() class?: string;
}

@Component({
  selector: 'app-table-row',
  template: `
    <tr [ngClass]="['border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted', class]">
      <ng-content></ng-content>
    </tr>
  `,
  standalone: true,
  imports: [CommonModule]
})
export class TableRowComponent {
  @Input() class?: string;
}

@Component({
  selector: 'app-table-head',
  template: `
    <th [ngClass]="['h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0', class]">
      <ng-content></ng-content>
    </th>
  `,
  standalone: true,
  imports: [CommonModule]
})
export class TableHeadComponent {
  @Input() class?: string;
}

@Component({
  selector: 'app-table-cell',
  template: `
    <td [ngClass]="['p-4 align-middle [&:has([role=checkbox])]:pr-0', class]">
      <ng-content></ng-content>
    </td>
  `,
  standalone: true,
  imports: [CommonModule]
})
export class TableCellComponent {
  @Input() class?: string;
}

// fullstack_nextjs/src/components/ui/table.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

const Table = React.forwardRef<
  HTMLTableElement,
  React.HTMLAttributes<HTMLTableElement>
>(({ className, ...props }, ref) => (
  <div className="relative w-full overflow-auto">
    <table
      ref={ref}
      className={cn("w-full caption-bottom text-sm", className)}
      {...props}
    />
  </div>
))
Table.displayName = "Table"

const TableHeader = React.forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <thead ref={ref} className={cn("[&_tr]:border-b", className)} {...props} />
))
TableHeader.displayName = "TableHeader"

const TableBody = React.forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <tbody
    ref={ref}
    className={cn("[&_tr:last-child]:border-0", className)}
    {...props}
  />
))
TableBody.displayName = "TableBody"

const TableFooter = React.forwardRef<
  HTMLTableSectionElement,
  React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
  <tfoot
    ref={ref}
    className={cn("border-t bg-muted/50 font-medium [&>tr]:last:border-b-0", className)}
    {...props}
  />
))
TableFooter.displayName = "TableFooter"

const TableRow = React.forwardRef<
  HTMLTableRowElement,
  React.HTMLAttributes<HTMLTableRowElement>
>(({ className, ...props }, ref) => (
  <tr
    ref={ref}
    className={cn(
      "border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted",
      className
    )}
    {...props}
  />
))
TableRow.displayName = "TableRow"

const TableHead = React.forwardRef<
  HTMLTableCellElement,
  React.ThHTMLAttributes<HTMLTableCellElement>
>(({ className, ...props }, ref) => (
  <th
    ref={ref}
    className={cn(
      "h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0",
      className
    )}
    {...props}
  />
))
TableHead.displayName = "TableHead"

const TableCell = React.forwardRef<
  HTMLTableCellElement,
  React.TdHTMLAttributes<HTMLTableCellElement>
>(({ className, ...props }, ref) => (
  <td
    ref={ref}
    className={cn("p-4 align-middle [&:has([role=checkbox])]:pr-0", className)}
    {...props}
  />
))
TableCell.displayName = "TableCell"

const TableCaption = React.forwardRef<
  HTMLTableCaptionElement,
  React.HTMLAttributes<HTMLTableCaptionElement>
>(({ className, ...props }, ref) => (
  <caption
    ref={ref}
    className={cn("mt-4 text-sm text-muted-foreground", className)}
    {...props}
  />
))
TableCaption.displayName = "TableCaption"

export {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
}
