// fullstack_nextjs/src/app/auth/login/page.tsx
"use client";

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/components/ui/use-toast';

interface FormData {
  email: string;
  password: string;
}

export default function LoginPage() {
  const { login } = useAuth();
  const router = useRouter();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);
  
  const { 
    register, 
    handleSubmit, 
    setError, 
    formState: { errors } 
  } = useForm<FormData>();
  
  const onSubmit = async (data: FormData) => {
    setIsLoading(true);
    try {
      const result = await login(data);
      
      toast({
        title: "Success",
        description: "Logged in successfully",
      });
      
      router.push(result.redirectTo || '/dashboard');
    } catch (error) {
      setError('password', { 
        type: 'server', 
        message: error instanceof Error ? error.message : 'Invalid email or password' 
      });
      
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : 'Login failed',
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <div className="w-full max-w-md space-y-6">
        <div className="text-center">
          <h1 className="text-2xl font-bold">Sign in to your account</h1>
          <p className="text-muted-foreground">Enter your credentials to access your account</p>
        </div>
        
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="Enter your email"
              {...register('email', { 
                required: 'Email is required',
                pattern: {
                  value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                  message: 'Invalid email address'
                }
              })}
              className="w-full"
              aria-invalid={errors.email ? 'true' : 'false'}
            />
            {errors.email && (
              <p className="text-sm text-destructive">{errors.email.message}</p>
            )}
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              placeholder="Enter your password"
              {...register('password', { 
                required: 'Password is required' 
              })}
              className="w-full"
              aria-invalid={errors.password ? 'true' : 'false'}
            />
            {errors.password && (
              <p className="text-sm text-destructive">{errors.password.message}</p>
            )}
          </div>

          <div className="flex items-center justify-between">
            <Link href="/auth/recover" className="text-sm text-primary hover:underline">
              Forgot your password?
            </Link>
            <Link href="/auth/register" className="text-sm text-primary hover:underline">
              Don't have an account?
            </Link>
          </div>

          <Button type="submit" className="w-full" disabled={isLoading}>
            {isLoading ? 'Signing in...' : 'Sign in'}
          </Button>
        </form>
        
        <div className="text-center">
          <Link href="/" className="text-sm text-muted-foreground hover:text-primary">
            ← Back to home
          </Link>
        </div>
      </div>
    </div>
  );
}

// 10x-cards-angular/src/app/features/auth/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login',
  standalone: true,
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent {

}

<div class="container flex items-center justify-center py-12">
  <div class="w-full max-w-md">
    <app-card class="p-6">
      <div class="text-center mb-6">
        <h1 class="text-2xl font-bold">Sign in to your account</h1>
        <p class="text-muted-foreground">Enter your credentials to access your account</p>
      </div>
      
      <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-4">
        <div class="space-y-2">
          <app-label for="email">Email</app-label>
          <app-input
            id="email"
            type="email"
            placeholder="Enter your email"
            formControlName="email"
            class="w-full"
          ></app-input>
          <p *ngIf="email?.errors?.['required'] && email?.touched" class="text-sm text-destructive">
            Email is required
          </p>
          <p *ngIf="email?.errors?.['email'] && email?.touched" class="text-sm text-destructive">
            Invalid email address
          </p>
        </div>
        
        <div class="space-y-2">
          <app-label for="password">Password</app-label>
          <app-input
            id="password"
            type="password"
            placeholder="Enter your password"
            formControlName="password"
            class="w-full"
          ></app-input>
          <p *ngIf="password?.errors?.['required'] && password?.touched" class="text-sm text-destructive">
            Password is required
          </p>
        </div>

        <p *ngIf="errorMessage" class="text-sm text-destructive text-center">{{ errorMessage }}</p>

        <app-button type="submit" class="w-full" [disabled]="isLoading">
          {{ isLoading ? 'Signing in...' : 'Sign in' }}
        </app-button>
      </form>
      
      <div class="mt-6 text-center text-sm">
        <a routerLink="/auth/recover" class="text-primary hover:underline">
          Forgot your password?
        </a>
      </div>
      <div class="mt-2 text-center text-sm">
        Don't have an account?
        <a routerLink="/auth/register" class="text-primary hover:underline">
          Register here
        </a>
      </div>
    </app-card>
  </div>
</div>
