// frontend_react/src/components/generation/GenerationHeader.tsx
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';

interface GenerationHeaderProps {
  name: string;
  flashcardCount: number;
  createdAt: string;
  onAddClick: () => void;
}

export function GenerationHeader({
  name,
  flashcardCount,
  createdAt,
  onAddClick
}: GenerationHeaderProps) {
  return (
    <div className="flex justify-between items-center mb-8">
      <div>
        <h1 className="text-3xl font-bold">{name}</h1>
        <div className="flex items-center gap-4 mt-2">
          <p className="text-muted-foreground">
            {flashcardCount} flashcard{flashcardCount !== 1 ? 's' : ''}
          </p>
          <span className="text-sm text-muted-foreground">
            Created: {new Date(createdAt).toLocaleDateString()}
          </span>
        </div>
      </div>
      <div className="flex gap-2">
        <Button 
          onClick={onAddClick}
          variant="outline"
        >
          Add Flashcard
        </Button>
        <Button asChild variant="outline">
          <Link to="/dashboard">Back to Dashboard</Link>
        </Button>
      </div>
    </div>
  );
}

// 10x-cards-angular/src/app/features/generations/generation-detail/generation-header.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-generation-header',
  template: `
    <div class="flex flex-col md:flex-row md:items-center md:justify-between py-4 border-b mb-4">
      <div>
        <h1 class="text-3xl font-bold">{{ name }}</h1>
        <p class="text-muted-foreground">{{ flashcardCount }} cards</p>
        <p class="text-xs text-gray-400">Created: {{ createdAt | date:'medium' }}</p>
      </div>
      <button class="btn btn-primary mt-4 md:mt-0" (click)="onAddClick.emit()">Add Flashcard</button>
    </div>
  `,
  standalone: true,
  imports: [DatePipe]
})
export class GenerationHeaderComponent {
  @Input() name!: string;
  @Input() flashcardCount!: number;
  @Input() createdAt!: string;
  @Output() onAddClick = new EventEmitter<void>();
}
