// 10x-cards-angular/src/app/shared/components/generations-table/generations-table.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ApiService, Generation } from '../../../core/services/api.service';
import { ButtonComponent } from '../button/button.component';
import { BadgeComponent } from '../badge/badge.component';

@Component({
  selector: 'app-generations-table',
  templateUrl: './generations-table.component.html',
  standalone: true,
  imports: [
    CommonModule, 
    RouterModule, 
    ButtonComponent, 
    BadgeComponent,
  ]
})
export class GenerationsTableComponent implements OnInit {
  @Output() error = new EventEmitter<string>();
  
  generations: Generation[] = [];
  loading = true;
  deletingId: number | null = null;

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.loadGenerations();
  }

  loadGenerations(): void {
    this.loading = true;
    this.apiService.getGenerations().subscribe({
      next: (data: any) => {
        console.log('API response for generations:', data);
        
        // Handle different possible response formats
        if (Array.isArray(data)) {
          this.generations = data;
        } else if (data && Array.isArray(data.generations)) {
          this.generations = data.generations;
        } else if (data && Array.isArray(data.data)) {
          this.generations = data.data;
        } else {
          console.warn('Unexpected API response format:', data);
          this.generations = [];
          this.error.emit(`Unexpected response format: ${typeof data}`);
        }
      },
      error: (err: any) => {
        console.error('Error loading generations:', err);
        const errorMessage = err.message || 'Failed to load generations';
        this.error.emit(errorMessage);
        this.generations = [];
      },
      complete: () => {
        this.loading = false;
      }
    });
  }

  handleDeleteGeneration(id: number, name: string): void {
    if (!confirm(`Are you sure you want to delete the generation "${name}"? This will also delete all associated flashcards.`)) {
      return;
    }

    this.deletingId = id;
    this.apiService.deleteGeneration(id).subscribe({
      next: () => {
        this.generations = this.generations.filter(g => g.id !== id);
      },
      error: (err: any) => {
        const errorMessage = err.message || 'Failed to delete generation';
        this.error.emit(errorMessage);
      },
      complete: () => {
        this.deletingId = null;
      }
    });
  }
}

<div class="space-y-4" *ngIf="!loading">
  <div class="flex justify-between items-center">
    <h2 class="text-xl font-semibold">Your Generations</h2>
    <app-button>
      <a routerLink="/generate">Generate New Flashcards</a>
    </app-button>
  </div>
  
  <div *ngIf="generations.length === 0" class="text-center py-12">
    <p class="text-muted-foreground mb-4">
      You haven't generated any flashcards yet.
    </p>
    <app-button>
      <a routerLink="/generate">Generate Your First Flashcards</a>
    </app-button>
  </div>

  <div *ngIf="generations.length > 0" class="border rounded-lg overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead>
        <tr>
          <th class="px-4 py-2 text-left">Name</th>
          <th class="px-4 py-2 text-left">Created</th>
          <th class="px-4 py-2 text-left">Updated</th>
          <th class="px-4 py-2 text-left">Flashcards</th>
          <th class="px-4 py-2 text-right">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let generation of generations">
          <td class="px-4 py-2">
            <a 
              [routerLink]="['/generations', generation.id]"
              class="font-medium hover:underline"
            >
              {{ generation.generation_name }}
            </a>
          </td>
          <td class="px-4 py-2 text-muted-foreground">
            {{ generation.created_at | date: 'mediumDate' }}
          </td>
          <td class="px-4 py-2 text-muted-foreground">
            {{ generation.updated_at | date: 'mediumDate' }}
          </td>
          <td class="px-4 py-2">
            <app-badge variant="secondary">
              {{ generation.flashcard_count || 0 }} cards
            </app-badge>
          </td>
          <td class="px-4 py-2 text-right">
            <div class="flex gap-2 justify-end">
              <app-button variant="outline" size="sm">
                <a [routerLink]="['/generations', generation.id]">
                  Manage
                </a>
              </app-button>
              <app-button
                variant="outline"
                size="sm"
                (click)="handleDeleteGeneration(generation.id, generation.generation_name)"
                [disabled]="deletingId === generation.id"
              >
                {{ deletingId === generation.id ? 'Deleting...' : 'Delete' }}
              </app-button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div *ngIf="loading" class="text-center py-8">
  <p class="text-muted-foreground">Loading generations...</p>
</div>

// fullstack_nextjs/src/components/GenerationsTable.tsx
"use client";

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { apiClient } from '@/lib/api';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';

interface Generation {
  id: number;
  generation_name: string;
  created_at: string;
  updated_at: string;
  user_id: string;
  flashcard_count?: number;
}

interface GenerationsTableProps {
  onError?: (error: string) => void;
}

export default function GenerationsTable({ onError }: GenerationsTableProps) {
  const [generations, setGenerations] = useState<Generation[]>([]);
  const [loading, setLoading] = useState(true);
  const [deletingId, setDeletingId] = useState<number | null>(null);

  useEffect(() => {
    loadGenerations();
  }, []);

  const loadGenerations = async () => {
    try {
      setLoading(true);
      const data = await apiClient.getGenerations();
      
      console.log('API response for generations:', data); // Debug log
      
      // Handle different possible response formats
      if (Array.isArray(data)) {
        setGenerations(data);
      } else if (data && Array.isArray(data.generations)) {
        setGenerations(data.generations);
      } else if (data && Array.isArray(data.data)) {
        setGenerations(data.data);
      } else {
        console.warn('Unexpected API response format:', data);
        setGenerations([]);
        onError?.(`Unexpected response format: ${typeof data}`);
      }
    } catch (err) {
      console.error('Error loading generations:', err); // Debug log
      const errorMessage = err instanceof Error ? err.message : 'Failed to load generations';
      onError?.(errorMessage);
      setGenerations([]); // Ensure we always have an array
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteGeneration = async (id: number, name: string) => {
    if (!confirm(`Are you sure you want to delete the generation "${name}"? This will also delete all associated flashcards.`)) {
      return;
    }

    try {
      setDeletingId(id);
      await apiClient.deleteGeneration(id);
      setGenerations(generations.filter(g => g.id !== id));
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to delete generation';
      onError?.(errorMessage);
    } finally {
      setDeletingId(null);
    }
  };

  if (loading) {
    return (
      <div className="text-center py-8">
        <p className="text-muted-foreground">Loading generations...</p>
      </div>
    );
  }

  if (generations.length === 0) {
    return (
      <div className="text-center py-12">
        <p className="text-muted-foreground mb-4">
          You haven't generated any flashcards yet.
        </p>
        <Button asChild>
          <Link href="/generate">Generate Your First Flashcards</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h2 className="text-xl font-semibold">Your Generations</h2>
        <Button asChild>
          <Link href="/generate">Generate New Flashcards</Link>
        </Button>
      </div>
      
      <div className="border rounded-lg">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Name</TableHead>
              <TableHead>Created</TableHead>
              <TableHead>Updated</TableHead>
              <TableHead>Flashcards</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {(generations || []).map((generation) => (
              <TableRow key={generation.id}>
                <TableCell>
                  <Link 
                    href={`/generations/${generation.id}`}
                    className="font-medium hover:underline"
                  >
                    {generation.generation_name}
                  </Link>
                </TableCell>
                <TableCell className="text-muted-foreground">
                  {new Date(generation.created_at).toLocaleDateString()}
                </TableCell>
                <TableCell className="text-muted-foreground">
                  {new Date(generation.updated_at).toLocaleDateString()}
                </TableCell>
                <TableCell>
                  <Badge variant="secondary">
                    {generation.flashcard_count || 0} cards
                  </Badge>
                </TableCell>
                <TableCell className="text-right">
                  <div className="flex gap-2 justify-end">
                    <Button
                      variant="outline"
                      size="sm"
                      asChild
                    >
                      <Link href={`/generations/${generation.id}`}>
                        Manage
                      </Link>
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDeleteGeneration(generation.id, generation.generation_name)}
                      disabled={deletingId === generation.id}
                    >
                      {deletingId === generation.id ? 'Deleting...' : 'Delete'}
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
