// frontend_angular/src/app/features/auth/register/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { CommonModule } from '@angular/common';
import { LabelComponent } from '../../../shared/components/label/label.component';
import { InputComponent } from '../../../shared/components/input/input.component';
import { ButtonComponent } from '../../../shared/components/button/button.component';
import { RegisterUserCommand } from '../../../core/types/index';
import { CardComponent } from '../../../shared/components/card/card.component';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  standalone: true,
  imports: [
    CommonModule, 
    ReactiveFormsModule, 
    RouterModule, 
    LabelComponent, 
    InputComponent, 
    ButtonComponent,
    CardComponent
  ]
})
export class RegisterComponent {
  registerForm: FormGroup;
  errorMessage?: string;
  isLoading = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.registerForm = this.fb.group({
      name: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
    });
  }

  onSubmit(): void {
    if (this.registerForm.invalid) {
      return;
    }
    
    this.isLoading = true;
    this.errorMessage = '';
    
    const command: RegisterUserCommand = this.registerForm.value;
    
    this.authService.register(command).subscribe({
      next: () => {
        this.router.navigate(['/auth/login']);
      },
      error: (err: any) => {
        this.errorMessage = err.message || 'Registration failed';
        this.isLoading = false;
      },
      complete: () => {
        this.isLoading = false;
      }
    });
  }

  get name() {
    return this.registerForm.get('name');
  }

  get email() {
    return this.registerForm.get('email');
  }

  get password() {
    return this.registerForm.get('password');
  }
}

<div class="container flex items-center justify-center py-12">
  <div class="w-full max-w-md">
    <app-card class="p-6">
      <div class="text-center mb-6">
        <h1 class="text-2xl font-bold">Create an account</h1>
        <p class="text-muted-foreground">Enter your details to create your account</p>
      </div>
      
      <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-4">
        <div class="space-y-2">
          <app-label for="name">Name</app-label>
          <app-input
            id="name"
            type="text"
            placeholder="Enter your name"
            formControlName="name"
            class="w-full"
          ></app-input>
          <p *ngIf="name?.errors?.['required'] && name?.touched" class="text-sm text-destructive">
            Name is required
          </p>
        </div>

        <div class="space-y-2">
          <app-label for="email">Email</app-label>
          <app-input
            id="email"
            type="email"
            placeholder="Enter your email"
            formControlName="email"
            class="w-full"
          ></app-input>
          <p *ngIf="email?.errors?.['required'] && email?.touched" class="text-sm text-destructive">
            Email is required
          </p>
          <p *ngIf="email?.errors?.['email'] && email?.touched" class="text-sm text-destructive">
            Invalid email address
          </p>
        </div>
        
        <div class="space-y-2">
          <app-label for="password">Password</app-label>
          <app-input
            id="password"
            type="password"
            placeholder="Enter your password"
            formControlName="password"
            class="w-full"
          ></app-input>
          <p *ngIf="password?.errors?.['required'] && password?.touched" class="text-sm text-destructive">
            Password is required
          </p>
          <p *ngIf="password?.errors?.['minlength'] && password?.touched" class="text-sm text-destructive">
            Password must be at least 6 characters
          </p>
        </div>

        <p *ngIf="errorMessage" class="text-sm text-destructive text-center">{{ errorMessage }}</p>

        <app-button type="submit" class="w-full" [disabled]="isLoading">
          {{ isLoading ? 'Creating account...' : 'Create account' }}
        </app-button>
      </form>
      
      <div class="mt-6 text-center text-sm">
        Already have an account?
        <a routerLink="/auth/login" class="text-primary hover:underline">
          Sign in
        </a>
      </div>
    </app-card>
  </div>
</div>

// fullstack_nextjs/src/app/auth/register/page.tsx
"use client";

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/components/ui/use-toast';

interface FormData {
  email: string;
  password: string;
  confirmPassword: string;
}

export default function RegisterPage() {
  const { register: registerUser } = useAuth();
  const router = useRouter();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);
  
  const { 
    register, 
    handleSubmit, 
    setError, 
    watch,
    reset,
    formState: { errors } 
  } = useForm<FormData>();
  
  // Get password value for confirmation validation
  const password = watch('password');
  
  const onSubmit = async (data: FormData) => {
    setIsLoading(true);
    try {
      const result = await registerUser({
        email: data.email,
        password: data.password,
        confirmPassword: data.confirmPassword
      });

      // Show success message
      toast({
        title: "Success",
        description: result.message || "Registration successful! Please check your email to verify your account.",
      });

      // Clear form
      reset();

      // Navigate to login after successful registration
      setTimeout(() => {
        router.push('/auth/login');
      }, 2000);

    } catch (error) {
      setError('email', { 
        type: 'server', 
        message: error instanceof Error ? error.message : 'Registration failed. Please try again.' 
      });
      
      toast({
        variant: "destructive",
        title: "Error",
        description: error instanceof Error ? error.message : "An unexpected error occurred. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <div className="w-full max-w-md space-y-6">
        <div className="text-center">
          <h1 className="text-2xl font-bold">Create your account</h1>
          <p className="text-muted-foreground">Enter your details to get started</p>
        </div>
        
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="Enter your email"
              {...register('email', { 
                required: 'Email is required',
                pattern: {
                  value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                  message: 'Invalid email address'
                }
              })}
              className="w-full"
              aria-invalid={errors.email ? 'true' : 'false'}
            />
            {errors.email && (
              <p className="text-sm text-destructive">{errors.email.message}</p>
            )}
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              placeholder="Choose a password"
              {...register('password', { 
                required: 'Password is required',
                minLength: {
                  value: 6,
                  message: 'Password must be at least 6 characters'
                }
              })}
              className="w-full"
              aria-invalid={errors.password ? 'true' : 'false'}
            />
            {errors.password && (
              <p className="text-sm text-destructive">{errors.password.message}</p>
            )}
          </div>

          <div className="space-y-2">
            <Label htmlFor="confirmPassword">Confirm Password</Label>
            <Input
              id="confirmPassword"
              type="password"
              placeholder="Confirm your password"
              {...register('confirmPassword', { 
                required: 'Please confirm your password',
                validate: (value: string) => value === password || "Passwords don't match"
              })}
              className="w-full"
              aria-invalid={errors.confirmPassword ? 'true' : 'false'}
            />
            {errors.confirmPassword && (
              <p className="text-sm text-destructive">{errors.confirmPassword.message}</p>
            )}
          </div>

          <div className="text-center">
            <Link href="/auth/login" className="text-sm text-primary hover:underline">
              Already have an account?
            </Link>
          </div>

          <Button type="submit" className="w-full" disabled={isLoading}>
            {isLoading ? 'Creating Account...' : 'Create Account'}
          </Button>
        </form>
        
        <div className="text-center">
          <Link href="/" className="text-sm text-muted-foreground hover:text-primary">
            ← Back to home
          </Link>
        </div>
      </div>
    </div>
  );
}
