// 10x-cards-angular/src/app/features/generations/generation-detail/new-flashcard-form.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { CreateFlashcardCommand } from '../../../core/types';

@Component({
  selector: 'app-new-flashcard-form',
  template: `
    <form [formGroup]="form" (ngSubmit)="submit()" class="space-y-4 p-4 border rounded bg-white">
      <div>
        <label>Question (Front)</label>
        <input class="input input-bordered w-full" formControlName="front" />
      </div>
      <div>
        <label>Answer (Back)</label>
        <input class="input input-bordered w-full" formControlName="back" />
      </div>
      <div>
        <label>Source</label>
        <select class="input input-bordered w-full" formControlName="source">
          <option value="manual">Manual</option>
          <option value="ai-edited">AI Edited</option>
        </select>
      </div>
      <div class="flex gap-2">
        <button class="btn btn-primary" type="submit" [disabled]="isSubmitting || form.invalid">Add</button>
        <button class="btn btn-secondary" type="button" (click)="onCancel.emit()">Cancel</button>
      </div>
    </form>
  `,
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule]
})
export class NewFlashcardFormComponent {
  @Input() generationId!: number;
  @Input() isSubmitting = false;
  @Output() onSubmit = new EventEmitter<CreateFlashcardCommand>();
  @Output() onCancel = new EventEmitter<void>();

  form: FormGroup;

  constructor(private fb: FormBuilder) {
    this.form = this.fb.group({
      front: ['', Validators.required],
      back: ['', Validators.required],
      source: ['manual', Validators.required]
    });
  }

  submit() {
    if (this.form.valid) {
      this.onSubmit.emit({
        ...this.form.value,
        generation_id: this.generationId,
        display_order: 1 // Will be set by parent
      });
    }
  }
}

// fullstack_nextjs/src/components/generation/NewFlashcardForm.tsx
"use client";

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { CreateFlashcardCommand } from '@/types';

interface NewFlashcardFormProps {
  generationId: number;
  onSubmit: (command: CreateFlashcardCommand) => Promise<void>;
  onCancel: () => void;
  isSubmitting?: boolean;
}

export function NewFlashcardForm({ generationId, onSubmit, onCancel, isSubmitting = false }: NewFlashcardFormProps) {
  const [front, setFront] = useState('');
  const [back, setBack] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!front.trim() || !back.trim()) return;

    const command: CreateFlashcardCommand = {
      front: front.trim(),
      back: back.trim(),
      source: 'manual',
      generation_id: generationId,
      display_order: 1 // This will be overridden by GenerationDetailPage
    };

    onSubmit(command);
    setFront('');
    setBack('');
  };

  return (
    <form onSubmit={handleSubmit} className="mb-8">
      <Card>
        <CardHeader>
          <CardTitle>Add New Flashcard</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="new-front">Question (Front)</Label>
              <Textarea
                id="new-front"
                value={front}
                onChange={(e) => setFront(e.target.value)}
                rows={4}
                className="resize-none"
              />
            </div>
            <div>
              <Label htmlFor="new-back">Answer (Back)</Label>
              <Textarea
                id="new-back"
                value={back}
                onChange={(e) => setBack(e.target.value)}
                rows={4}
                className="resize-none"
              />
            </div>
          </div>
          <div className="flex justify-end gap-2 mt-4">
            <Button type="button" variant="outline" onClick={onCancel}>
              Cancel
            </Button>
            <Button 
              type="submit"
              disabled={isSubmitting || !front.trim() || !back.trim()}
            >
              {isSubmitting ? 'Adding...' : 'Add Flashcard'}
            </Button>
          </div>
        </CardContent>
      </Card>
    </form>
  );
}
