// fullstack_nextjs/src/app/dashboard/page.tsx
"use client";

import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import GenerationsTable from '@/components/GenerationsTable';

export default function DashboardPage() {
  const { user, logout } = useAuth();
  const [error, setError] = useState<string | null>(null);

  const handleLogout = async () => {
    try {
      await logout();
    } catch (error) {
      console.error('Logout failed:', error);
    }
  };

  const handleError = (errorMessage: string) => {
    setError(errorMessage);
  };

  return (
    <div className="max-w-6xl mx-auto">
      <div className="flex justify-between items-center mb-8">
        <div>
          <h1 className="text-3xl font-bold">Dashboard</h1>
          <p className="text-muted-foreground">Welcome back, {user?.email}</p>
        </div>
        <Button onClick={handleLogout} variant="outline">
          Logout
        </Button>
      </div>

      {error && (
        <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-md">
          <p className="text-red-700">{error}</p>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={() => setError(null)}
            className="mt-2"
          >
            Dismiss
          </Button>
        </div>
      )}

      <GenerationsTable onError={handleError} />
    </div>
  );
}

// 10x-cards-angular/src/app/features/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ButtonComponent } from '../../shared/components/button/button.component';
import { GenerationsTableComponent } from '../../shared/components/generations-table/generations-table.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
  standalone: true,
  imports: [CommonModule, ButtonComponent, GenerationsTableComponent]
})
export class DashboardComponent implements OnInit {
  error: string | null = null;

  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    // Component initialization
  }

  get user() {
    return this.authService.user;
  }

  handleLogout(): void {
    this.authService.logout().subscribe({
      next: () => {
        this.router.navigate(['/auth/login']);
      },
      error: (error) => {
        console.error('Logout failed:', error);
      }
    });
  }

  handleError(errorMessage: string): void {
    this.error = errorMessage;
  }

  dismissError(): void {
    this.error = null;
  }
}

<div class="max-w-6xl mx-auto">
  <div class="flex justify-between items-center mb-8">
    <div>
      <h1 class="text-3xl font-bold">Dashboard</h1>
      <p class="text-muted-foreground">Welcome back, {{ user?.email }}</p>
    </div>
    <app-button variant="outline" (click)="handleLogout()">
      Logout
    </app-button>
  </div>

  <div *ngIf="error" class="mb-6 p-4 bg-red-50 border border-red-200 rounded-md">
    <p class="text-red-700">{{ error }}</p>
    <app-button 
      variant="outline" 
      size="sm" 
      (click)="dismissError()"
      class="mt-2"
    >
      Dismiss
    </app-button>
  </div>

  <app-generations-table (error)="handleError($event)"></app-generations-table>
</div>
