// fullstack_nextjs/src/app/generate/page.tsx
"use client";

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { apiClient } from '@/lib/api';
import { useToast } from '@/components/ui/use-toast';

interface FlashcardProposal {
  front: string;
  back: string;
  approved: boolean;
  edited: boolean;
}

export default function GeneratePage() {
  const [text, setText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [step, setStep] = useState<'input' | 'review'>('input');
  const [proposals, setProposals] = useState<FlashcardProposal[]>([]);
  const [generationId, setGenerationId] = useState<number | null>(null);
  const router = useRouter();
  const { toast } = useToast();

  const handleLoadSample = async () => {
    try {
      const response = await fetch('/sampleContent.md');
      const sampleText = await response.text();
      setText(sampleText);
      toast({
        title: "Success",
        description: "Sample content loaded.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Failed to load sample content.",
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (text.length < 1000) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Text must be at least 1000 characters long.",
      });
      return;
    }

    if (text.length > 10000) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Text cannot exceed 10000 characters.",
      });
      return;
    }

    setIsLoading(true);
    try {
      const result = await apiClient.generateFlashcards({ text });
      
      // Transform the proposals to include approval state
      const proposalsWithState = result.flashcardProposals.map(proposal => ({
        ...proposal,
        approved: true, // Default to approved
        edited: false
      }));
      
      setProposals(proposalsWithState);
      setGenerationId(result.generation_id);
      setStep('review');
      
      toast({
        title: "Success",
        description: `Generated ${result.stats.generated_count} flashcards! Please review them.`,
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to generate flashcards. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSave = async () => {
    if (!generationId) return;

    setIsLoading(true);
    try {
      const approvedCards = proposals
        .filter(p => p.approved)
        .map(p => ({
          front: p.front,
          back: p.back,
          source: p.edited ? 'ai-edited' as const : 'ai-full' as const
        }));

      await apiClient.updateGeneration(generationId, { flashcards: approvedCards });
      
      toast({
        title: "Success",
        description: "Flashcards saved successfully!",
      });
      
      router.push(`/generations/${generationId}`);
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to save flashcards. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleProposalUpdate = (index: number, updates: Partial<FlashcardProposal>) => {
    setProposals(current => 
      current.map((proposal, i) => 
        i === index ? { ...proposal, ...updates } : proposal
      )
    );
  };

  const handleBulkAction = (action: 'approve' | 'reject') => {
    setProposals(current =>
      current.map(proposal => ({
        ...proposal,
        approved: action === 'approve'
      }))
    );
  };

  if (step === 'review') {
    return (
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold">Review Flashcards</h1>
          <p className="text-muted-foreground">
            Review and edit the generated flashcards before saving
          </p>
        </div>

        <div className="mb-4 flex gap-4">
          <Button onClick={() => handleBulkAction('approve')} variant="outline">
            Approve All
          </Button>
          <Button onClick={() => handleBulkAction('reject')} variant="outline">
            Reject All
          </Button>
        </div>

        <div className="space-y-4 mb-6">
          {proposals.map((proposal, index) => (
            <div key={index} className="border rounded-lg p-4">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={proposal.approved}
                    onChange={(e) => handleProposalUpdate(index, { approved: e.target.checked })}
                    className="h-4 w-4"
                  />
                  <span className="text-sm font-medium">Card {index + 1}</span>
                </div>
              </div>
              <div className="space-y-2">
                <textarea
                  value={proposal.front}
                  onChange={(e) => handleProposalUpdate(index, { front: e.target.value, edited: true })}
                  className="w-full p-2 border rounded"
                  placeholder="Front side"
                />
                <textarea
                  value={proposal.back}
                  onChange={(e) => handleProposalUpdate(index, { back: e.target.value, edited: true })}
                  className="w-full p-2 border rounded"
                  placeholder="Back side"
                />
              </div>
            </div>
          ))}
        </div>

        <div className="flex gap-4">
          <Button onClick={handleSave} disabled={isLoading}>
            {isLoading ? 'Saving...' : 'Save Approved Cards'}
          </Button>
          <Button type="button" variant="outline" onClick={() => setStep('input')}>
            Back to Input
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold">Generate Flashcards</h1>
        <p className="text-muted-foreground">
          Paste your text below and we'll create flashcards for you using AI
        </p>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="space-y-2 relative">
          <div className="flex justify-between items-center">
            <Label htmlFor="text">Your Text</Label>
            <Button type="button" variant="link" onClick={handleLoadSample}>
              Load Sample Content
            </Button>
          </div>
          <textarea
            id="text"
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Paste your text here (minimum 1000 characters, maximum 10000)..."
            className="w-full min-h-[400px] p-3 border rounded-md resize-y"
            disabled={isLoading}
          />
          <div className="text-sm text-muted-foreground">
            Characters: {text.length} / 10000 (minimum: 1000)
          </div>
        </div>

        <div className="flex gap-4">
          <Button type="submit" disabled={isLoading || text.length < 1000}>
            {isLoading ? 'Generating...' : 'Generate Flashcards'}
          </Button>
          <Button type="button" variant="outline" onClick={() => router.push('/dashboard')}>
            Cancel
          </Button>
        </div>
      </form>
    </div>
  );
}

// 10x-cards-angular/src/app/features/generate/generate.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { ApiService } from '../../core/services/api.service';
import { ButtonComponent } from '../../shared/components/button/button.component';
import { LabelComponent } from '../../shared/components/label/label.component';
import { TextareaComponent } from '../../shared/components/textarea/textarea.component';
import { GenerateFlashcardsCommand, GenerationResultDTO } from '../../core/types/index';

interface FlashcardProposal {
  front: string;
  back: string;
  approved: boolean;
  edited: boolean;
}

@Component({
  selector: 'app-generate',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    ButtonComponent,
    LabelComponent,
    TextareaComponent
  ],
  templateUrl: './generate.component.html',
  styleUrl: './generate.component.scss'
})
export class GenerateComponent {
  generateForm: FormGroup;
  isLoading = false;
  step: 'input' | 'review' = 'input';
  proposals: FlashcardProposal[] = [];
  generationId: number | null = null;
  errorMessage = '';
  successMessage = '';

  constructor(
    private fb: FormBuilder,
    private apiService: ApiService,
    private router: Router,
    private http: HttpClient
  ) {
    this.generateForm = this.fb.group({
      text: ['', [Validators.required, Validators.minLength(1000), Validators.maxLength(10000)]]
    });
  }

  get text() {
    return this.generateForm.get('text');
  }

  get textValue() {
    return this.text?.value || '';
  }

  handleLoadSample(): void {
    this.http.get('/sampleContent.md', { responseType: 'text' }).subscribe({
      next: (sampleText) => {
        this.generateForm.patchValue({ text: sampleText });
        this.showSuccess('Sample content loaded.');
      },
      error: (error) => {
        this.showError('Failed to load sample content.');
      }
    });
  }

  onSubmit(): void {
    if (this.generateForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';
      this.successMessage = '';

      const command: GenerateFlashcardsCommand = {
        text: this.textValue
      };

      this.apiService.generateFlashcards(command).subscribe({
        next: (result: GenerationResultDTO) => {
          // Transform the proposals to include approval state
          const proposalsWithState = result.flashcardProposals.map(proposal => ({
            ...proposal,
            approved: true, // Default to approved
            edited: false
          }));

          this.proposals = proposalsWithState;
          this.generationId = result.generation_id;
          this.step = 'review';

          this.showSuccess(`Generated ${result.stats.generated_count} flashcards! Please review them.`);
        },
        error: (error) => {
          this.showError(error.message || 'Failed to generate flashcards. Please try again.');
        },
        complete: () => {
          this.isLoading = false;
        }
      });
    }
  }

  handleSave(): void {
    if (!this.generationId) return;

    this.isLoading = true;
    this.errorMessage = '';
    this.successMessage = '';

    const approvedCards = this.proposals
      .filter(p => p.approved)
      .map(p => ({
        front: p.front,
        back: p.back,
        source: p.edited ? 'ai-edited' as const : 'ai-full' as const
      }));

    this.apiService.updateGeneration(this.generationId, { flashcards: approvedCards }).subscribe({
      next: () => {
        this.showSuccess('Flashcards saved successfully!');
        this.router.navigate(['/generations', this.generationId]);
      },
      error: (error) => {
        this.showError(error.message || 'Failed to save flashcards. Please try again.');
      },
      complete: () => {
        this.isLoading = false;
      }
    });
  }

  handleProposalUpdate(index: number, updates: Partial<FlashcardProposal>): void {
    this.proposals = this.proposals.map((proposal, i) => 
      i === index ? { ...proposal, ...updates } : proposal
    );
  }

  handleBulkAction(action: 'approve' | 'reject'): void {
    this.proposals = this.proposals.map(proposal => ({
      ...proposal,
      approved: action === 'approve'
    }));
  }

  backToInput(): void {
    this.step = 'input';
  }

  cancel(): void {
    this.router.navigate(['/dashboard']);
  }

  private showError(message: string): void {
    this.errorMessage = message;
    this.successMessage = '';
  }

  private showSuccess(message: string): void {
    this.successMessage = message;
    this.errorMessage = '';
  }
}

<!-- Input Step -->
<div class="max-w-4xl mx-auto" *ngIf="step === 'input'">
  <div class="mb-8">
    <h1 class="text-3xl font-bold">Generate Flashcards</h1>
    <p class="text-muted-foreground">
      Paste your text below and we'll create flashcards for you using AI
    </p>
  </div>

  <form [formGroup]="generateForm" (ngSubmit)="onSubmit()" class="space-y-6">
    <div class="space-y-2 relative">
      <div class="flex justify-between items-center">
        <app-label for="text">Your Text</app-label>
        <app-button type="button" variant="link" (click)="handleLoadSample()">
          Load Sample Content
        </app-button>
      </div>
      <app-textarea
        id="text"
        formControlName="text"
        placeholder="Paste your text here (minimum 1000 characters, maximum 10000)..."
        class="w-full min-h-[400px] resize-y"
        [disabled]="isLoading"
      ></app-textarea>
      <div class="text-sm text-muted-foreground">
        Characters: {{ textValue.length }} / 10000 (minimum: 1000)
      </div>
      <div *ngIf="text?.errors?.['required'] && text?.touched" class="text-sm text-destructive">
        Text is required
      </div>
      <div *ngIf="text?.errors?.['minlength'] && text?.touched" class="text-sm text-destructive">
        Text must be at least 1000 characters
      </div>
      <div *ngIf="text?.errors?.['maxlength'] && text?.touched" class="text-sm text-destructive">
        Text cannot exceed 10000 characters
      </div>
    </div>

    <div *ngIf="errorMessage" class="text-sm text-destructive">{{ errorMessage }}</div>
    <div *ngIf="successMessage" class="text-sm text-green-600">{{ successMessage }}</div>

    <div class="flex gap-4">
      <app-button 
        type="submit" 
        [disabled]="isLoading || textValue.length < 1000"
      >
        {{ isLoading ? 'Generating...' : 'Generate Flashcards' }}
      </app-button>
      <app-button type="button" variant="outline" (click)="cancel()">
        Cancel
      </app-button>
    </div>
  </form>
</div>

<!-- Review Step -->
<div class="max-w-4xl mx-auto" *ngIf="step === 'review'">
  <div class="mb-8">
    <h1 class="text-3xl font-bold">Review Flashcards</h1>
    <p class="text-muted-foreground">
      Review and edit the generated flashcards before saving
    </p>
  </div>

  <div class="mb-4 flex gap-4">
    <app-button (click)="handleBulkAction('approve')" variant="outline">
      Approve All
    </app-button>
    <app-button (click)="handleBulkAction('reject')" variant="outline">
      Reject All
    </app-button>
  </div>

  <div class="space-y-4 mb-6">
    <div 
      *ngFor="let proposal of proposals; let i = index" 
      class="border rounded-lg p-4"
    >
      <div class="flex items-center justify-between mb-2">
        <div class="flex items-center gap-2">
          <input
            type="checkbox"
            [checked]="proposal.approved"
            (change)="handleProposalUpdate(i, { approved: $any($event.target).checked })"
            class="h-4 w-4"
          />
          <span class="text-sm font-medium">Card {{ i + 1 }}</span>
        </div>
      </div>
      <div class="space-y-2">
        <textarea
          [value]="proposal.front"
          (input)="handleProposalUpdate(i, { front: $any($event.target).value, edited: true })"
          class="w-full p-2 border rounded"
          placeholder="Front side"
        ></textarea>
        <textarea
          [value]="proposal.back"
          (input)="handleProposalUpdate(i, { back: $any($event.target).value, edited: true })"
          class="w-full p-2 border rounded"
          placeholder="Back side"
        ></textarea>
      </div>
    </div>
  </div>

  <div *ngIf="errorMessage" class="mb-4 text-sm text-destructive">{{ errorMessage }}</div>
  <div *ngIf="successMessage" class="mb-4 text-sm text-green-600">{{ successMessage }}</div>

  <div class="flex gap-4">
    <app-button (click)="handleSave()" [disabled]="isLoading">
      {{ isLoading ? 'Saving...' : 'Save Approved Cards' }}
    </app-button>
    <app-button type="button" variant="outline" (click)="backToInput()">
      Back to Input
    </app-button>
  </div>
</div>
