// 10x-cards-angular/src/app/features/auth/recover/recover.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../core/services/auth.service';
import { LabelComponent } from '../../../shared/components/label/label.component';
import { InputComponent } from '../../../shared/components/input/input.component';
import { ButtonComponent } from '../../../shared/components/button/button.component';
import { RecoverPasswordCommand } from '../../../core/types/index';

@Component({
  selector: 'app-recover',
  templateUrl: './recover.component.html',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule, LabelComponent, InputComponent, ButtonComponent]
})
export class RecoverComponent {
  recoverForm: FormGroup;
  message?: string;
  errorMessage?: string;
  isLoading = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.recoverForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
    });
  }

  onSubmit(): void {
    if (this.recoverForm.invalid) {
      return;
    }
    
    this.isLoading = true;
    this.errorMessage = '';
    this.message = '';
    
    const command: RecoverPasswordCommand = this.recoverForm.value;
    
    this.authService.recover(command).subscribe({
      next: () => {
        this.message = 'If an account with this email exists, a recovery link has been sent.';
      },
      error: (error) => {
        this.errorMessage = error.message || 'An error occurred. Please try again.';
        this.isLoading = false;
      },
      complete: () => {
        this.isLoading = false;
      }
    });
  }

  get email() {
    return this.recoverForm.get('email');
  }
}

<div class="flex items-center justify-center min-h-[60vh]">
  <div class="w-full max-w-md space-y-6">
    <div class="text-center">
      <h1 class="text-2xl font-bold">Recover your password</h1>
      <p class="text-muted-foreground">Enter your email address and we'll send you a recovery link</p>
    </div>
    
    <form [formGroup]="recoverForm" (ngSubmit)="onSubmit()" class="space-y-6">
      <div class="space-y-2">
        <app-label for="email">Email</app-label>
        <app-input
          id="email"
          type="email"
          placeholder="Enter your email"
          formControlName="email"
          class="w-full"
        ></app-input>
        <p *ngIf="email?.errors?.['required'] && email?.touched" class="text-sm text-destructive">
          Email is required
        </p>
        <p *ngIf="email?.errors?.['email'] && email?.touched" class="text-sm text-destructive">
          Invalid email address
        </p>
        <p *ngIf="message" class="text-sm text-green-600">{{ message }}</p>
        <p *ngIf="errorMessage" class="text-sm text-destructive">{{ errorMessage }}</p>
      </div>

      <div class="flex items-center justify-center">
        <a routerLink="/auth/login" class="text-sm text-primary hover:underline">
          Remember your password? Sign in
        </a>
      </div>

      <app-button type="submit" class="w-full" [disabled]="isLoading">
        {{ isLoading ? 'Sending...' : 'Send recovery link' }}
      </app-button>
    </form>
    
    <div class="text-center">
      <a routerLink="/" class="text-sm text-muted-foreground hover:text-primary">
        ← Back to home
      </a>
    </div>
  </div>
</div>

// fullstack_nextjs/src/app/auth/recover/page.tsx
"use client";

import { useState } from 'react';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/components/ui/use-toast';

interface FormData {
  email: string;
}

export default function RecoverPage() {
  const { recover } = useAuth();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);
  
  const { 
    register, 
    handleSubmit, 
    reset,
    formState: { errors } 
  } = useForm<FormData>();
  
  const onSubmit = async (data: FormData) => {
    setIsLoading(true);
    try {
      const result = await recover(data);
      
      toast({
        title: "Success",
        description: result.message || "Password reset instructions sent to your email.",
      });
      
      reset();
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to send recovery email. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <div className="w-full max-w-md space-y-6">
        <div className="text-center">
          <h1 className="text-2xl font-bold">Reset your password</h1>
          <p className="text-muted-foreground">Enter your email to receive reset instructions</p>
        </div>
        
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="Enter your email"
              {...register('email', { 
                required: 'Email is required',
                pattern: {
                  value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                  message: 'Invalid email address'
                }
              })}
              className="w-full"
              aria-invalid={errors.email ? 'true' : 'false'}
            />
            {errors.email && (
              <p className="text-sm text-destructive">{errors.email.message}</p>
            )}
          </div>

          <Button type="submit" className="w-full" disabled={isLoading}>
            {isLoading ? 'Sending...' : 'Send Reset Instructions'}
          </Button>
        </form>
        
        <div className="text-center space-y-2">
          <Link href="/auth/login" className="text-sm text-primary hover:underline">
            Back to login
          </Link>
          <br />
          <Link href="/" className="text-sm text-muted-foreground hover:text-primary">
            ← Back to home
          </Link>
        </div>
      </div>
    </div>
  );
}
